---
- hosts: clients
  become: yes
  vars:

  tasks:
    - name: Setting DNS server...
      shell: 'echo "nameserver 8.8.8.8" >> /etc/resolv.conf'
    - name: Installing software-propeties-common...
      package: name={{item}} state=latest update_cache=yes
      with_items: {'software-properties-common','dirmngr','gpg'}
    - name: Adding repo key...
      apt_key:
        keyserver: 'hkp://keyserver.ubuntu.com:80'
        id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    - name: Adding repository...
      apt_repository:
        repo: 'deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main'
    - name: Installing MongoDB...
      package: name=mongodb-org state=latest update_cache=yes

    #Instala: software-propeties-common y dirmngr
    #apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    #add-apt-repository 'deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main'
    #apt update
    #apt install mongodb-org
    #systemctl start mongod
    #systemctl enable mongod
    #mongo --eval 'db.runCommand({ connectionStatus: 1 })'
    #donde:
    #security:
      #authorization: enabled

    #restart

    #mongo
    #use admin
    #db.createUser(
  #{
  #  user: "mongoAdmin", 
  #  pwd: "changeMe", 
  #  roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  #}
#)
